application: cloud-computing-assigment
version: 9
runtime: php55
api_version: 1
threadsafe: yes

runtime_config:
    document_root: web


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: index.php

- url: /products.php
  script: products.php

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images
  